//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kursova
{
    using System;
    using System.Collections.Generic;
    
    public partial class guarantee
    {
        public int guar_id { get; set; }
        public int order_id { get; set; }
        public Nullable<System.DateTime> date_from { get; set; }
        public System.DateTime date_to { get; set; }
    
        public virtual orders orders { get; set; }
    }
}
